build:
    environment:
        php:
            version: "8.2"
filter:
    excluded_paths:
        - 'lib/components/*'
        - 'vendor/*'
        - 'tests'
    paths: {  }
tools:
    php_mess_detector:
        enabled: true
        filter:
            excluded_paths:
                - 'lib/components/*'
                - 'vendor/*'
                - 'public/themes/*'
                - '.github.*'
            paths: {  }
    php_code_sniffer:
        enabled: false
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'lib/components/*'
                - 'vendor/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths:
            - 'lib/components/*'
            - 'vendor/*'
        filter:
            excluded_paths:
                - 'lib/components/*'
                - 'vendor/*'
                - 'public/themes/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'lib/components/*'
                - 'vendor/*'
            paths: {  }
    php_loc:
        enabled: true
        excluded_dirs:
            - 'lib/components/*'
            - 'vendor/*'
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'lib/components/*'
                - 'vendor/*'
            paths: {  }
